毕业项目源码和数据库/Game/Controllers/GoodsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Models;

namespace Game.Controllers
{
    public class GoodsController : Controller
    {
        GameShoppingEntities db = new GameShoppingEntities();
        // GET: Goods
        
        public ActionResult Index(int? typeId)
        {
            List<Good> gList = db.Good.Where(p => typeId == null || p.TypeID == typeId).ToList();
            ViewBag.TypeList = db.Type.ToList();
            ViewBag.ShopCarCount = db.ShopCar.Count();
            return View(gList);
        }
        public ActionResult AddCar(int GoodId)
        {
            ShopCar shopCar = new ShopCar()
            {
                GoodID = GoodId
            };
            db.ShopCar.Add(shopCar);
            db.SaveChanges();
            return View();
        }
        public ActionResult ShoppingCar()
        {
            return View(db.ShopCar.ToList());
        }
    }
}

毕业项目源码和数据库/Game/Controllers/HeroesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BLL;
using Models;
namespace Game.Controllers
{
    public class HeroesController : Controller
    {
        //上下文类
        HeroesBLL heroBLL = new HeroesBLL();

        // GET: LOL
        public ActionResult Index()
        {
            ViewBag.hero = heroBLL.Look1();
            return View();
        }
        /// <summary>
        /// 新增
        /// </summary>
        /// <returns></returns>
        public ActionResult Insert()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Insert(Heroes heroes)
        {
            int retult = heroBLL.Insert1(heroes);
            if (retult == 1)
            {
                return RedirectToAction("Index");
            }
            return View();
        }
        /// <summary>
        /// 删除
        /// </summary>
        /// <returns></returns>
        public ActionResult Delete(int id)
        {
            int retult = heroBLL.Delete1(id);
            if (retult == 1)
            {
                return RedirectToAction("Index");
            }
            return View();
        }
        /// <summary>
        /// 修改
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult Edit(int id)
        {
            ViewBag.hero = heroBLL.EditDetail1(id);
            return View();
        }
        [HttpPost]
        public ActionResult Edit(Heroes heroes)
        {
            int result = heroBLL.Edit1(heroes);
            if (result == 1)
            {
                return RedirectToAction("Index");
            }
            return View();
        }
    }
}

毕业项目源码和数据库/Game/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Game.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

毕业项目源码和数据库/Game/Controllers/TypesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Models;

namespace Game.Controllers
{
    
    public class TypesController : Controller
    {
        GameShoppingEntities db = new GameShoppingEntities();
        // GET: Types
        public ActionResult Index()
        {
            return View(db.Type.ToList());
        }
        [HttpPost]
        public ActionResult FindChlidren(int Pid)
        {
            db.Configuration.LazyLoadingEnabled = false;
            var typeList = db.Type.Where(p => p.PID == Pid);
            return Json(typeList);
        }
    }
}

毕业项目源码和数据库/Game/Views/Goods/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@{
    List<Models.Type> tList = ViewBag.TypeList;
}
@model List<Models.Good>
<div class="row">
    <div class="panel" style="padding-left:2em">
        @foreach (var item in tList.Where(p => p.PID == null))
        {
            <p>
                <strong>@item.TypeName</strong>:
                @foreach (var item1 in tList.Where(a => a.PID == item.ID))
                {
                    <a href=" " class="btn btn-link">
                        @item1.TypeName
                    </a>
                }
            </p>
        }
    </div>
</div>

<div class="row">
    @foreach (var item in Model)
    {
        <div class="col-sm-6 col-md-3">
            <div class="thumbnail">
                <img src="~/Content/Goods/@item.Photo" alt="..." />
                <div class="caption">
                    <h3>@string.Format("{0:C}", item.SellingPrice)</h3>
                    <h4 style="text-decoration:line-through;color:gray;">@item.CostPrice</h4>
                    <p>@item.GoodName</p>
                    <p>
                        <a href=" " class="btn btn-danger" role="button" onclick="AddCart(@item.Id)">加入购物车</a>
                        <a href="#" class="btn btn-default" role="button">购买</a>
                    </p>
                </div>
            </div>
        </div>
    }
</div>




@section scripts{
    <script type="text/javascript">function AddCart(a)
        {
            var GoodId = a;
            $.ajax({
                url: "/Goods/AddCar",
                data: { "GoodId": GoodId },
                success: function ()
                {
                    alert("成功加入购物车！我在购物车等你哟！");
                }
            })
        }</script>
}

毕业项目源码和数据库/Game/Views/Goods/ShoppingCar.cshtml
@{
    ViewBag.Title = "ShoppingCar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using Models;
@model List<ShopCar>
@{
    ViewBag.Title = "ShoppingCar";
    var price = "price";
}

<h2>购物车</h2>
<table class="table table-bordered table-hover">
    <thead class="bg-warning">
        <tr>
            <td>全选</td>
            <td>商品</td>
            <td>单价</td>
            <td>购买数量</td>
            <td>小计</td>
            <td>操作</td>
        </tr>
    </thead>
    @foreach (var item in Model.GroupBy(p => p.GoodID))
    {
        var count = Model.Where(p => p.GoodID == item.Key).Count();
        var firstGood = item.First();
        <tr>
            <td width="10%"><input type="checkbox" GooodID="@firstGood.GoodID" name="GoodID" /></td>
            <td width="50%"><img src="~/Content/Goods/@firstGood.Good.Photo" height="100" />@firstGood.Good.GoodName</td>
            <td>@firstGood.Good.SellingPrice</td>
            <td width="10%">
                <div class="input-group">
                    <span class="input-group-addon">-</span>
                    <input type="text" value="@count" class="form-control" />
                    <span class="input-group-addon">+</span>
                </div>
            </td>
            <td>
                <div id="@price@firstGood.GoodID">
                    @{
                        var GoodPrice = count * firstGood.Good.SellingPrice;

                    }
                    @GoodPrice
                </div>
            </td>
            <td>
                <a href="#" class="btn btn-danger">删除</a>
            </td>
        </tr>
    }
</table>
<div class="row">
    <div class="text-right">
        总价:<span class="text-danger">￥xx</span>&nbsp;<a href="#" class="btn btn-danger btn-lg">去结算</a>
    </div>
</div>

毕业项目源码和数据库/Game/Views/Heroes/Edit.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

@using Models;
@{
    Heroes heroes = ViewBag.hero;
}

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Edit</title>
</head>
<body>
    <h1>更新英雄</h1>
    @using (Html.BeginForm("Edit"))
    {

        <input type="hidden" value="@heroes.Id" />
        <div>
            <label>姓名：</label>
            <input type="text" value="@heroes.Name" name="Name" />
        </div>

        <div>
            <label>图片：</label>
            <input type="text" value="@heroes.Photo" name="Photo" />
        </div>

        <div>
            <label>Q币：</label>
            <input type="text" value="@heroes.Q_Coin" name="Q_Coin" />
        </div>

        <div>
            <label>微信：</label>
            <input type="text" value="@heroes.Weixin" name="Weixin" />
        </div>

        <div>
            <input type="submit" value="提交" />
        </div>
    }
</body>
</html>

毕业项目源码和数据库/Game/Views/Heroes/Index.cshtml
@{
    ViewBag.Title = "Index";
}
@using Models;
@{
    List<Heroes> herros = ViewBag.hero;
}


<h3><a href="~/LOL/Insert">新增</a></h3>

<table class="table-bordered table-hover">
    <tr>
        <th>图片</th>
        <th>编号</th>
        <th>名字</th>
        <th>Q币</th>
        <th>微信</th>
        <th>操作</th>
    </tr>
    @foreach (var item in herros)
    {
        <tr>

            <td><img src="~/Content/images（net机试素材）/@item.Photo" width="100" height="50"></td>
            <td>@item.Id</td>
            <td>@item.Name</td>
            <td>@item.Q_Coin</td>
            <td>@string.Format("{0:C}", item.Weixin)</td>
            <td>
                <a href="/LOL/Edit/@item.Id" class="btn-primary">编辑</a>
                <a href="/LOL/Delete/@item.Id" onclick="return confirm('你确定要删除嘛？')" class="btn-danger">删除</a>
            </td>
        </tr>
    }
</table>

毕业项目源码和数据库/Game/Views/Heroes/Insert.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title></title>
</head>
<body>
    <h1>新增英雄</h1>
    @using (Html.BeginForm())
    {
        <div>
            <label>姓名：</label>
            @Html.TextBox("Name")
        </div>

        <div>
            <label>图片：</label>
            @Html.TextBox("Photo")
        </div>

        <div>
            <label>Q币：</label>
            @Html.TextBox("Q_Coin")
        </div>

        <div>
            <label>微信：</label>
            @Html.TextBox("Weixin")
        </div>

        <div>
            <input type="submit" value="提交" />
        </div>
    }
</body>
</html>

毕业项目源码和数据库/Game/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

毕业项目源码和数据库/Game/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

毕业项目源码和数据库/Game/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

毕业项目源码和数据库/Game/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - 我的 ASP.NET 应用程序</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("应用程序名称", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("主页", "Index", "Home")</li>
                    <li>@Html.ActionLink("关于", "About", "Home")</li>
                    <li>@Html.ActionLink("商品类型管理", "Index", "Types")</li>
                    <li>@Html.ActionLink("商品", "Index", "Goods")</li>
                    <li>@Html.ActionLink("联系方式", "Contact", "Home")</li>
                </ul>
                <ul>
                    <li>
                        <a href=" " class="glyphicon glyphicon-shopping-cart">购物车
                        <span class="badge">@ViewBag.ShopCarCount</span>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - 我的 ASP.NET 应用程序</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

毕业项目源码和数据库/Game/Views/Types/Index.cshtml
@{
    ViewBag.Title = "Index";
    var menu = "menu";
}
@model List<Models.Type>
<ul style="list-style:none">
    @foreach (var item in Model.Where(p => p.PID == null))
    {
        <li data-toggle="collapse" data-target="#@menu@item.ID" dataValue="@item.ID" onclick="FindChildren(this)">
            <input type="checkbox" />@item.TypeName
            <div id="@menu@item.ID" class="collapse">
                @foreach (var item1 in Model.Where(p => p.PID == item.ID))
                {
                    <p style="text-indent:2em;">@item1.TypeName</p>
                }
            </div>

        </li>
    }
</ul>


@section scripts{
    <script type="text/javascript">
        function FindChildren(a) {
            var value = $(a).attr("dataValue");
            $.ajax({
                type: "post",
                async: true,
                url: "/Types/FindChildren",
                dataType:"Json",
                data: {
                    "Pid": value
                },
                success: function (data) {
                    console.log(data);
                }
            })
        }
    </script>
}